---

# Credit: https://mths.be/macos

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
- name: Close any open System Preferences panes
  shell: osascript -e 'tell application "System Preferences" to quit'
  changed_when: false

- name: Set the icon size of Dock items
  osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: float
    value: 60
  notify:
    - killall Dock

- name: Set Dock orientation
  osx_defaults:
    domain: com.apple.dock
    key: orientation
    type: string
    value: "bottom"
  notify:
    - killall Dock

- name: Set whether the Dock automatically hides
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
  notify:
    - killall Dock

# Dock items
# ----------

# Shell command returns only filenames (excluding paths) from within
# /Applications or one further level down.
- name: Get list of .app files in /Applications
  shell: find . -name '*.app' -maxdepth 2 | sed 's/^\.\///'
  args:
    chdir: /Applications
  register: installed_apps
  changed_when: false

- name: Wipe all default app icons from the Dock
  command: defaults write com.apple.dock persistent-apps -array
  notify: killall Dock

# - Only adds apps to the Dock that are already installed
- name: Add applications to Dock
  command: >
    defaults write com.apple.dock persistent-apps -array-add
    '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/{{ item }}</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
  with_items: "{{ dock_apps | intersect(installed_apps.stdout_lines) }}"
  notify: killall Dock
