---

# Credit: https://mths.be/macos

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
- name: Close any open System Preferences panes
  shell: osascript -e 'tell application "System Preferences" to quit'
  changed_when: false

- name: Set whether the Dock automatically hides
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: "{{ macos_dock_autohide }}"
  notify:
    - killall Dock

- name: Set the icon size of Dock items
  osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: float
    value: "{{ macos_dock_icon_size }}"
  notify:
    - killall Dock

- name: Set Dock orientation
  osx_defaults:
    domain: com.apple.dock
    key: orientation
    type: string
    value: "{{ macos_dock_orientation }}"
  notify:
    - killall Dock

# Dock items
# ----------

- name: Remove current persistent apps from the Dock
  command: defaults write com.apple.dock persistent-apps -array
  notify: killall Dock

# TODO: Add support for non-app Dock items such as directories.
# TODO: Set -maxdepth via a default variable.

# Lists full paths to all apps in /Applications & ~/Applications.
- name: Get list of apps in /Applications & ~/Applications
  shell: "find {{ item }} -name '*.app' -maxdepth 2"
  with_items:
     - /Applications
     - ~/Applications
  register: installed_apps
  changed_when: false

# # Lists full paths to all apps in /Applications or one further directory down.
# - name: Get list of apps in /Applications
#   shell: find /Applications -name '*.app' -maxdepth 2
#   register: apps_in_applications
#   changed_when: false
# 
# # Lists full paths to all apps in ~/Applications or one further directory down.
# - name: Get list of apps in ~/Applications
#   shell: find ~/Applications -name '*.app' -maxdepth 2
#   register: apps_in_user_applications
#   changed_when: false

# - name: Combine lists of apps
#   set_fact:
#     installed_apps: "{{ apps_in_applications.stdout_lines + apps_in_user_applications.stdout_lines }}"

- name: Debug installed_apps
  debug:
    var: installed_apps

# Only adds apps to the Dock that exist on the system.
- name: Add applications to Dock
  command: >
    defaults write com.apple.dock persistent-apps -array-add
    '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>{{ item }}</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
  with_items: "{{ macos_dock_apps | intersect(installed_apps) }}"
  notify: killall Dock
